name: monolith2microservice

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5671:5671"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ../rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ../rabbitmq/ssl/:/etc/rabbitmq/ssl/:ro
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  client_app:
    build:
      context: ../Client/client_app
    container_name: client_app
    depends_on:
      - rabbitmq

  machine_app:
    build:
      context: ../Machine/machine_app
    container_name: machine_app
    depends_on:
      - rabbitmq
      - client_app
    volumes:
      - ../rabbitmq/ssl/:/app/ssl/:ro 

  api_gateway:
    build:
      context: ../APIGateway
    container_name: api_gateway
    ports:
      - "8002:8002"
    depends_on:
      - machine_app
      - client_app
      - rabbitmq

volumes:
  rabbitmq_data:
