name: monolith2microservice

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWD:-guest}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ../rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ../rabbitmq/ssl/:/etc/rabbitmq/ssl/:ro
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - app-net

  client_app:
    build:
      context: ../
      dockerfile: /Auth/client_app/Dockerfile
    container_name: client_app
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ../rabbitmq/ssl/:/etc/rabbitmq/ssl/:ro
    networks:
      - app-net

  machine_app:
    build:
      context: ../
      dockerfile: Machine/Dockerfile
    container_name: machine_app
    depends_on:
      - rabbitmq
      - client_app
    volumes:
      - ../rabbitmq/ssl/:/etc/rabbitmq/ssl/:ro
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_SQLITE_DATABASE_MACHINE_URI}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    restart: on-failure
    networks:
      - app-net

  order_app:
    build:
      context: ../
      dockerfile: Order/order_app/Dockerfile
    container_name: order_app
    depends_on:
      - rabbitmq
      - client_app
    command: >
      sh -c "sleep 10 && hypercorn app.main:app --bind 0.0.0.0:8000"
    volumes:
      - ../rabbitmq/ssl/:/etc/rabbitmq/ssl/:ro
    networks:
      - app-net

  api_gateway:
    build:
      context: ../APIGateway
    container_name: api_gateway
    ports:
      - "8002:8002"
    depends_on:
      - machine_app
      - client_app
      - order_app
      - rabbitmq
    networks:
      - app-net

volumes:
  rabbitmq_data:

networks:
  app-net: